---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3-2-1b-instruct
  labels:
    app: llama3-2-1b-instruct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama3-2-1b-instruct
  template:
    metadata:
      labels:
        app: llama3-2-1b-instruct
    spec:
      containers:
      - name: llama3-2-1b-instruct
        image: nvcr.io/nim/meta/llama-3.2-1b-instruct:1.12.0
        ports:
        - containerPort: 8000
        env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ngc-api-key
              key: NGC_API_KEY
        volumeMounts:
        - name: llama3-2-1b-nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
            nvidia.com/gpu: "1"
          requests: 
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: "1"
      volumes:
      - name: llama3-2-1b-nim-cache
        persistentVolumeClaim:
          claimName: llama3-2-1b-nim-cache
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      imagePullSecrets:
      - name: nim-pull-secret
