---
# STORAGE_CLASS_NAME is defined in kustomization.yaml and applied here.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama3-2-1b-nim-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: $(STORAGE_CLASS_NAME)
