---
# storageClassName is replaced by env_preparation/deploy_root_application.sh during deployment.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama3-2-1b-nim-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  # storageClassName: placeholder-storageclass
