apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llms

resources:
- deployment.yaml
- pvc.yaml
- service.yaml

configMapGenerator:
- name: pvc-storageclass
  literals:
  - storageClassName=ocs-external-storagecluster-ceph-rbd

vars:
- name: STORAGE_CLASS_NAME
  objref:
    kind: ConfigMap
    name: pvc-storageclass
    apiVersion: v1
  fieldref:
    fieldpath: data.storageClassName
