---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phi-3-mini-nim-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api-key
type: Opaque
stringData:
  api-key: API_KEY_GENERATED_FROM_NGC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-3-mini-instruct
  labels:
    app: phi-3-mini-instruct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phi-3-mini-instruct
  template:
    metadata:
      labels:
        app: phi-3-mini-instruct
    spec:
      containers:
      - name: phi-3-mini-instruct
        image: nvcr.io/nim/microsoft/phi-3-mini-4k-instruct:latest
        ports:
        - containerPort: 8000
        env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ngc-api-key
              key: api-key
        volumeMounts:
        - name: phi-3-mini-nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            cpu: "8"
            memory: 24Gi
            nvidia.com/gpu: "1"
          requests: 
            cpu: "6"
      volumes:
      - name: phi-3-mini-nim-cache
        persistentVolumeClaim:
          claimName: phi-3-mini-nim-cache
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      imagePullSecrets:
      - name: nim-pull-secret
---
kind: Service
apiVersion: v1
metadata:
  name: phi-3-mini-instruct
  labels:
    app: phi-3-mini-instruct
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: phi-3-mini-instruct
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: phi-3-mini-instruct
  labels:
    app: phi-3-mini-instruct
spec:
  to:
    kind: Service
    name: phi-3-mini-instruct
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None