---
# storageClassName is replaced by env_preparation/deploy_root_application.sh during deployment.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-ceph-rbd
  # storageClassName: placeholder-storageclass