---
# STORAGE_CLASS_NAME is defined in kustomization.yaml and applied here.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: $(STORAGE_CLASS_NAME)