---
# argocd-apps/minio.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: openshift-gitops  # or your Argo CD namespace
spec:
  project: s3-storage
  source:
    repoURL: https://github.com/MohammadB88/genai-application.git
    targetRevision: main
    path: s3_storage/minio_on_openshift      # directory containing kustomization.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: s3-storage             # target namespace for the app

  syncPolicy:
    automated:
      prune: true                # remove resources if deleted in Git
      selfHeal: true             # recreate if someone changes them
    syncOptions:
      - CreateNamespace=true   # automatically create the namespace if it doesn't exist