---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ai-assistant
spec:
  to:
    kind: Service
    name: ai-assistant-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 8888
